// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkcqlvmdvpmsbhwkntlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrY3Fsdm1kdnBtc2Jod2tudGx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzM1OTgsImV4cCI6MjA3MzcwOTU5OH0.kh5m64mSUjxeMsNOaa2VsTTtiVQe1x500gurlRi8FJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});